name: ideal_dart_code_handler
description: A sample command-line application.
version: 1.1.5
homepage: https://idealapp.fr/fr/home

environment:
  sdk: '>=2.10.0 <3.0.0'

executables:
  ideal_dart_code_handler: ideal_dart_code_handler

dependencies:
  path: ^1.7.0
  analyzer: ^2.2.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
